name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: rustfmt, clippy

    - name: Check
      uses: actions-rs/cargo@v1
      with:
        command: check
  
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install stable
      uses: actions-rs/toolchain@v1
      with:
          toolchain: stable
          components: rustfmt, clippy

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        command: build

    - name: Test
      uses: actions-rs/cargo@v1
      with:
        command: test